name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .kube directory
      run: mkdir -p ~/.kube

    - name: Decode and Set Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config

    - name: Deploy manifests to AKS
      run: kubectl apply -f k8s/
